# Generated by Django 5.2.16 on 2026-07-30 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(choices=[('Brain Cancer', 'Brain Cancer'), ('Breast Cancer', 'Breast Cancer'), ('Lung Cancer', 'Lung Cancer'), ('Liver Cancer', 'Liver Cancer'), ('Colon Cancer', 'Colon Cancer')], max_length=50)),
                ('medical_image', models.ImageField(upload_to='scans/')),
                ('prediction', models.CharField(choices=[('Cancerous', 'Cancerous'), ('Non-Cancerous', 'Non-Cancerous')], default='Cancerous', max_length=20)),
                ('confidence', models.FloatField(default=95.0)),
                ('probability', models.FloatField(default=0.95)),
                ('processing_time', models.FloatField(default=1.2)),
                ('estimated_stage', models.CharField(default='Stage II (Localized)', max_length=50)),
                ('model_explanation', models.TextField(blank=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
