# Generated by Django 5.2.16 on 2026-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='auto_detected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='organ_confidence',
            field=models.FloatField(default=98.5),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_type',
            field=models.CharField(choices=[('Auto-Detect', '✨ Auto-Detect Organ & Cancer Type (AI Automated)'), ('Brain Cancer', 'Brain Cancer'), ('Breast Cancer', 'Breast Cancer'), ('Lung Cancer', 'Lung Cancer'), ('Liver Cancer', 'Liver Cancer'), ('Colon Cancer', 'Colon Cancer')], default='Auto-Detect', max_length=50),
        ),
    ]
