# Generated by Django 5.2.16 on 2026-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosis_auto_detected_diagnosis_organ_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_type',
            field=models.CharField(choices=[('Auto-Detect', '✨ Auto-Detect Organ & Cancer Type (AI Automated)'), ('Brain Cancer', 'Brain Cancer'), ('Breast Cancer', 'Breast Cancer'), ('Lung Cancer', 'Lung Cancer'), ('Liver Cancer', 'Liver Cancer'), ('Colon Cancer', 'Colon Cancer'), ('Kidney Cancer', 'Kidney Cancer')], default='Auto-Detect', max_length=50),
        ),
    ]
