# Generated by Django 5.2.16 on 2026-07-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_alter_diagnosis_cancer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='auto_detected',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='organ_confidence',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='cancer_type',
            field=models.CharField(choices=[('Brain Cancer', 'Brain Cancer'), ('Breast Cancer', 'Breast Cancer'), ('Lung Cancer', 'Lung Cancer'), ('Liver Cancer', 'Liver Cancer'), ('Kidney Cancer', 'Kidney Cancer')], default='Brain Cancer', max_length=50),
        ),
    ]
