# Generated by Copilot on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_remove_diagnosis_auto_detected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='medical_image',
            field=models.FileField(upload_to='scans/'),
        ),
    ]