# Generated by Django 5.2.16 on 2026-07-30 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, default='+1 (555) 019-2834', max_length=20)),
                ('title', models.CharField(default='Senior Oncologist', max_length=100)),
                ('department', models.CharField(default='Diagnostic Oncology & Radiology', max_length=100)),
                ('bio', models.TextField(blank=True, default='Board-certified oncologist specializing in early-stage detection and AI-assisted clinical workflow integration.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
